### ISSUE TITLE
Entity Textures not appearing

### ISSUE THREAD

**Issue by lartts** [Guild-Hall/MHFC#31] opened 2021-01-29 11:25 UTC
Most of the entity textures and animations do not appear, look at the Tigrex for example:
![2021-01-29_18 17 34](https://user-images.githubusercontent.com/74058566/106269186-c5358900-625e-11eb-8722-af073ecaf022.png)

With the only exceptions are the Nargacuga and Kirin:
![2021-01-29_18 18 01](https://user-images.githubusercontent.com/74058566/106269274-e72f0b80-625e-11eb-957f-73eed6530ac1.png)
![2021-01-29_18 19 00](https://user-images.githubusercontent.com/74058566/106269299-ebf3bf80-625e-11eb-9493-2111fa9cdc20.png)

**Comment by WorldSEnder** [comment] 2021-01-29 15:00
Can you post what versions of mhfc *and* mcanm you are using? It might have something to do with an update there.

**Comment by lartts** [comment] 2021-01-29 15:04
I am using
mhfc-1.4.10-1.12.2.jar
and
MCAnm-2.7.5.157+1.12.2.jar

**Comment by WorldSEnder** [comment] 2021-01-30 06:20
Do you have any other mods installed, if so, please post them as well, the best would be to have a full client log, also.

This is not reproducible for me running the development branch for 1.12.2, all textures load fine, with only mhfc, mcanm and worldedit pulled in as dependencies.

**Comment by lartts** [comment] 2021-01-30 06:41
Ok sure
<img width="443" alt="Screenshot 2021-01-30 133644" src="https://user-images.githubusercontent.com/74058566/106349472-9839b280-6300-11eb-826c-73a206e96fec.png">
<img width="446" alt="Screenshot 2021-01-30 133721" src="https://user-images.githubusercontent.com/74058566/106349473-996adf80-6300-11eb-8e1a-98b30b08f396.png">
<img width="423" alt="Screenshot 2021-01-30 133812" src="https://user-images.githubusercontent.com/74058566/106349474-9a037600-6300-11eb-82a2-8a1a517eca2f.png">
<img width="431" alt="Screenshot 2021-01-30 133843" src="https://user-images.githubusercontent.com/74058566/106349475-9b34a300-6300-11eb-83ae-2928de89ba29.png">
<img width="410" alt="Screenshot 2021-01-30 133900" src="https://user-images.githubusercontent.com/74058566/106349476-9b34a300-6300-11eb-853d-0d29a651d3de.png">

**Comment by WorldSEnder** [comment] 2021-01-30 06:44
- Can you edit that and get me a list that I can copy, paste and search as text?
- Can you try just running mhfc, mcanm and worldedit and getting rid of all the other mods to see if the problem persists? If yes, that's a serious issue, if no, it's an incompatibility with another mod and I'm not going to try out all the few billion possible combinations of mods here (but I have a few hunches which mods it might be)

**Comment by lartts** [comment] 2021-01-30 07:50
Hmm, removing Ice and Fire solves the problem. Why does it produce that bug tho?

**Comment by WorldSEnder** [comment] 2021-01-30 08:08
I wish I knew, but investigating that will take a lot more time. Thank you for trying it out, was that Ice_and_Fire the only mod you removed, i.e. are you positive it's caused by that mod exactly? In any case, since 1.12.2 was quite a while ago I would note it down somewhere as a known incompatibility (I would have guessed on LLibrary, which Ice and Fire depends on).

If you want to spend some more time, you can work out a *minimal* mod configuration that reproduces the bug and post that below, maybe it helps someone else in the future. Other than that, I even think mhfc is not responsible for the behaviour, merely effected by it, but that's just guesswork at the end of the day.

**Comment by WorldSEnder** [comment] 2021-01-31 13:24
Closing this, as I don't think there's anything *we* can do about it. Reopen if you find out anything new :+1:

**Closed as completed by WorldSEnder** 2021-01-31 13:24 UTC
